files:
  - source: /src/main/res/values/strings.xml
    translation: /src/main/res/values-%locale%/strings.xml
    languages_mapping:
      locale:
        cs: cs
        de: de
        es-ES: es-rES
        fr: fr
        it: it
        ja: ja
        pt-BR: pt-rBR
        ru: ru
  - source: /src/main/res/values/arrays.xml
    translation: /src/main/res/values-%locale%/arrays.xml
    languages_mapping:
      locale:
        cs: cs
        de: de
        es-ES: es-rES
        fr: fr
        it: it
        ja: ja
        pt-BR: pt-rBR
        ru: ru